typography_spectrum: 0.3524338728748262
color:
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
  brandStrength: 0.4697083053179085
  lightness: 0.7166527125518769
  saturation: 0.22571744653396308
  rhythmicContrast: 0.712546531111002
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4224315593019128
analytics:
  google: null
  facebook: null
  twitter: null
name: MichaelTucker
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Mike @ Oroville Toyota Chevrolet
description: Your Local Internet Sales Advisor
purpose: []
